/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.intsuperior.vista;

import ec.edu.intsuperior.controlador.Controlador;
import ec.edu.intsuperior.controlador.ControladorArqueoCaja;
import ec.edu.intsuperior.controlador.ControladorCliente;
import ec.edu.intsuperior.controlador.ControladorCotizacion;
import ec.edu.intsuperior.controlador.ControladorProducto;
import ec.edu.intsuperior.controlador.ControladorProveedor;
import ec.edu.intsuperior.controlador.ControladorUsuarios;
import ec.edu.intsuperior.controlador.ControladorVentas;
import javax.swing.JFrame;

/**
 * Pantalla principal del Sistema de Facturacion
 * @author Vinueza Fernando 
 */
public class WCentral extends javax.swing.JFrame {
private final Controlador controlador;
private final ControladorCliente c_cliente=new ControladorCliente();
private final ControladorProveedor c_proveedor=new ControladorProveedor();
private final ControladorProducto c_producto =new ControladorProducto();
private final ControladorVentas c_ventas=new ControladorVentas();
private final ControladorCotizacion c_cotizacion=new ControladorCotizacion();
private final ControladorUsuarios c_usuarios=new ControladorUsuarios();
private final ControladorArqueoCaja c_arqueocaja=new ControladorArqueoCaja();
    /**
     * Creates new form WCentral
     * @param controlador
     */
    public WCentral(Controlador controlador) {
        initComponents();
        this.controlador=controlador;
    }
    public void addJFrame(javax.swing.JInternalFrame j){
    jDContenedor.add(j);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDContenedor = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMantenimiento = new javax.swing.JMenu();
        jmProductos = new javax.swing.JMenuItem();
        jmClientes = new javax.swing.JMenuItem();
        jmProveedores = new javax.swing.JMenuItem();
        jmVarios = new javax.swing.JMenuItem();
        jmBodega = new javax.swing.JMenu();
        jmBodegaIngresos = new javax.swing.JMenuItem();
        jmBodegaEgresos = new javax.swing.JMenuItem();
        jmSeguridad = new javax.swing.JMenu();
        jmPermisos = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenuItem();
        jmFacturacion = new javax.swing.JMenu();
        jmVentas = new javax.swing.JMenuItem();
        jmCotizacion = new javax.swing.JMenuItem();
        jmDevolucionVentas = new javax.swing.JMenuItem();
        jmCompras = new javax.swing.JMenu();
        jmCompra = new javax.swing.JMenuItem();
        jmPedido = new javax.swing.JMenuItem();
        jmDevolucionCompras = new javax.swing.JMenuItem();
        jmContabilidad = new javax.swing.JMenu();
        jmRetenciones = new javax.swing.JMenuItem();
        jmNotaCredito = new javax.swing.JMenuItem();
        jmNotaDebito = new javax.swing.JMenuItem();
        jmAsientosContables = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmInventario = new javax.swing.JMenuItem();
        jmReporteContabilidad = new javax.swing.JMenuItem();
        jmArqueoCaja = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jmManual = new javax.swing.JMenuItem();
        jmManualTecnico = new javax.swing.JMenuItem();
        jmAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jDContenedor.setBackground(new java.awt.Color(0, 51, 204));
        jDContenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDContenedor.setAutoscrolls(true);
        jDContenedor.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/favicon.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jDContenedor.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDContenedorLayout = new javax.swing.GroupLayout(jDContenedor);
        jDContenedor.setLayout(jDContenedorLayout);
        jDContenedorLayout.setHorizontalGroup(
            jDContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDContenedorLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(742, 742, 742))
        );
        jDContenedorLayout.setVerticalGroup(
            jDContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDContenedorLayout.createSequentialGroup()
                .addGap(0, 189, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jDContenedor);

        jmMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/Recycle_Bin_Full_24276.png"))); // NOI18N
        jmMantenimiento.setText("Mantenimiento");
        jmMantenimiento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/App-icons-icon.png"))); // NOI18N
        jmProductos.setText("Productos");
        jmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProductosActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmProductos);

        jmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/user_person_customer_man_1532.png"))); // NOI18N
        jmClientes.setText("Clientes");
        jmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClientesActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmClientes);

        jmProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/Groups-Meeting-Dark-icon (1).png"))); // NOI18N
        jmProveedores.setText("Proveedores");
        jmProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProveedoresActionPerformed(evt);
            }
        });
        jmMantenimiento.add(jmProveedores);

        jmVarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/administrative_tools_15497.png"))); // NOI18N
        jmVarios.setText("Varios");
        jmMantenimiento.add(jmVarios);

        jmBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/supervisor_people_man_you_2840.png"))); // NOI18N
        jmBodega.setText("Bodega");

        jmBodegaIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/mail-inbox_36095.png"))); // NOI18N
        jmBodegaIngresos.setText("Ingresos");
        jmBodega.add(jmBodegaIngresos);

        jmBodegaEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/mail-outbox_36093.png"))); // NOI18N
        jmBodegaEgresos.setText("Egresos");
        jmBodega.add(jmBodegaEgresos);

        jmMantenimiento.add(jmBodega);

        jmSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/key_1564.png"))); // NOI18N
        jmSeguridad.setText("Seguridad");

        jmPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/loginlockrefreshincircularbutton_80241.png"))); // NOI18N
        jmPermisos.setText("Permisos");
        jmPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPermisosActionPerformed(evt);
            }
        });
        jmSeguridad.add(jmPermisos);

        jmUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/userkdmfemale_person_woman_5920.png"))); // NOI18N
        jmUsuarios.setText("Usuarios");
        jmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosActionPerformed(evt);
            }
        });
        jmSeguridad.add(jmUsuarios);

        jmMantenimiento.add(jmSeguridad);

        jMenuBar1.add(jmMantenimiento);

        jmFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/bar_code_22177.png"))); // NOI18N
        jmFacturacion.setText("Facturacion");
        jmFacturacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/Electronic_billing_machine_Icon_64.png"))); // NOI18N
        jmVentas.setText("Ventas");
        jmVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVentasActionPerformed(evt);
            }
        });
        jmFacturacion.add(jmVentas);

        jmCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/business_ordering_pencil_table_2333.png"))); // NOI18N
        jmCotizacion.setText("Cotizacion");
        jmCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCotizacionActionPerformed(evt);
            }
        });
        jmFacturacion.add(jmCotizacion);

        jmDevolucionVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/mail-inbox_36095.png"))); // NOI18N
        jmDevolucionVentas.setText("Devoluciones");
        jmDevolucionVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDevolucionVentasActionPerformed(evt);
            }
        });
        jmFacturacion.add(jmDevolucionVentas);

        jMenuBar1.add(jmFacturacion);

        jmCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/Box_1_35524.png"))); // NOI18N
        jmCompras.setText("Compras");
        jmCompras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/invoice_22150.png"))); // NOI18N
        jmCompra.setText("Compra");
        jmCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCompraActionPerformed(evt);
            }
        });
        jmCompras.add(jmCompra);

        jmPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/folder_102333.png"))); // NOI18N
        jmPedido.setText("Pedido");
        jmPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPedidoActionPerformed(evt);
            }
        });
        jmCompras.add(jmPedido);

        jmDevolucionCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/mail-outbox_36093.png"))); // NOI18N
        jmDevolucionCompras.setText("Devolucion");
        jmDevolucionCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDevolucionComprasActionPerformed(evt);
            }
        });
        jmCompras.add(jmDevolucionCompras);

        jMenuBar1.add(jmCompras);

        jmContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/editnote_edi_9512.png"))); // NOI18N
        jmContabilidad.setText("Contabilidad");
        jmContabilidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmRetenciones.setText("Retenciones");
        jmContabilidad.add(jmRetenciones);

        jmNotaCredito.setText("Notas de Credito");
        jmContabilidad.add(jmNotaCredito);

        jmNotaDebito.setText("Nota de Debito");
        jmContabilidad.add(jmNotaDebito);

        jmAsientosContables.setText("Asientos Contables");
        jmContabilidad.add(jmAsientosContables);

        jMenuBar1.add(jmContabilidad);

        jmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/table_graph_6191.png"))); // NOI18N
        jmReportes.setText("Reportes");
        jmReportes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/file_cab_15475.png"))); // NOI18N
        jmInventario.setText("Inventario");
        jmReportes.add(jmInventario);

        jmReporteContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/bar_chart_22178.png"))); // NOI18N
        jmReporteContabilidad.setText("Contabilidad");
        jmReportes.add(jmReporteContabilidad);

        jmArqueoCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/Banking_00019_A_icon-icons.com_59819.png"))); // NOI18N
        jmArqueoCaja.setText("Arqueo de Caja");
        jmArqueoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmArqueoCajaActionPerformed(evt);
            }
        });
        jmReportes.add(jmArqueoCaja);

        jMenuBar1.add(jmReportes);

        jmAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/help_920.png"))); // NOI18N
        jmAyuda.setText("Ayuda");
        jmAyuda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/User_Manual-80_icon-icons.com_57245.png"))); // NOI18N
        jmManual.setText("Manual");
        jmAyuda.add(jmManual);

        jmManualTecnico.setText("Manual Tecnco");
        jmAyuda.add(jmManualTecnico);

        jmAcercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/Home.png"))); // NOI18N
        jmAcercade.setText("Acerca de..");
        jmAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAcercadeActionPerformed(evt);
            }
        });
        jmAyuda.add(jmAcercade);

        jMenuBar1.add(jmAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCompraActionPerformed
        // TODO add your handling code here:
       // controlador.getFacturacion(this, "Compras");
    }//GEN-LAST:event_jmCompraActionPerformed

    private void jmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClientesActionPerformed
       c_cliente.getClienteProveedor(this,"Clientes");
    }//GEN-LAST:event_jmClientesActionPerformed

    private void jmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosActionPerformed
        // TODO add your handling code here:
        c_usuarios.getUsuario(this);
    }//GEN-LAST:event_jmUsuariosActionPerformed

    private void jmVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVentasActionPerformed
        // TODO add your handling code here:
       c_ventas.getFacturacion(this);
    }//GEN-LAST:event_jmVentasActionPerformed

    private void jmCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCotizacionActionPerformed
        // TODO add your handling code here:
                c_cotizacion.getFacturacion(this);

    }//GEN-LAST:event_jmCotizacionActionPerformed

    private void jmDevolucionVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDevolucionVentasActionPerformed
        // TODO add your handling code here:
               // controlador.getFacturacion(this, "Devoluciones Ventas");

    }//GEN-LAST:event_jmDevolucionVentasActionPerformed

    private void jmPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPedidoActionPerformed
        // TODO add your handling code here:
     //  controlador.getFacturacion(this, "Pedido Compras");
    }//GEN-LAST:event_jmPedidoActionPerformed

    private void jmDevolucionComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDevolucionComprasActionPerformed
        // TODO add your handling code here:
        //   controlador.getFacturacion(this, "Devoluciones Compras");
    }//GEN-LAST:event_jmDevolucionComprasActionPerformed

    private void jmProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProveedoresActionPerformed
        // TODO add your handling code here:
        c_proveedor.getClienteProveedor(this);
    }//GEN-LAST:event_jmProveedoresActionPerformed

    private void jmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProductosActionPerformed
        // TODO add your handling code here:
        c_producto.getProducto(this);
    }//GEN-LAST:event_jmProductosActionPerformed

    private void jmPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPermisosActionPerformed
        // TODO add your handling code here:
        c_usuarios.showPermisos(this,"Permisos de Usuario");
    }//GEN-LAST:event_jmPermisosActionPerformed

    private void jmAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAcercadeActionPerformed
        // TODO add your handling code here:
        controlador.getAcercade();
    }//GEN-LAST:event_jmAcercadeActionPerformed

    private void jmArqueoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmArqueoCajaActionPerformed
        // TODO add your handling code here:
        c_arqueocaja.getArqueCaja();
    }//GEN-LAST:event_jmArqueoCajaActionPerformed
int a=0;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         try{
        if(a==0){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/kamila.png")));
            a++;
        }else{
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/intsuperior/recursos/favicon.png"))); 
        a=0;
        }
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WCentral().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDContenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jmAcercade;
    public javax.swing.JMenuItem jmArqueoCaja;
    public javax.swing.JMenuItem jmAsientosContables;
    public javax.swing.JMenu jmAyuda;
    public javax.swing.JMenu jmBodega;
    public javax.swing.JMenuItem jmBodegaEgresos;
    public javax.swing.JMenuItem jmBodegaIngresos;
    public javax.swing.JMenuItem jmClientes;
    public javax.swing.JMenuItem jmCompra;
    public javax.swing.JMenu jmCompras;
    public javax.swing.JMenu jmContabilidad;
    public javax.swing.JMenuItem jmCotizacion;
    public javax.swing.JMenuItem jmDevolucionCompras;
    public javax.swing.JMenuItem jmDevolucionVentas;
    public javax.swing.JMenu jmFacturacion;
    public javax.swing.JMenuItem jmInventario;
    public javax.swing.JMenu jmMantenimiento;
    public javax.swing.JMenuItem jmManual;
    public javax.swing.JMenuItem jmManualTecnico;
    public javax.swing.JMenuItem jmNotaCredito;
    public javax.swing.JMenuItem jmNotaDebito;
    public javax.swing.JMenuItem jmPedido;
    public javax.swing.JMenuItem jmPermisos;
    public javax.swing.JMenuItem jmProductos;
    public javax.swing.JMenuItem jmProveedores;
    public javax.swing.JMenuItem jmReporteContabilidad;
    public javax.swing.JMenu jmReportes;
    public javax.swing.JMenuItem jmRetenciones;
    public javax.swing.JMenu jmSeguridad;
    public javax.swing.JMenuItem jmUsuarios;
    public javax.swing.JMenuItem jmVarios;
    public javax.swing.JMenuItem jmVentas;
    // End of variables declaration//GEN-END:variables

    public void addJFrame(JFrame wc) {
       jDContenedor.add(wc);//To change body of generated methods, choose Tools | Templates.
    }
}
